### ISSUE TITLE
Voucher and Memebership card vs Get It

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#824] opened 2022-10-05 09:19 UTC
When a voucher/membership card is on the home screen the GET IT is removed
If the voucher/membership card is deleted the GET IT is displayed

**Comment by hawkbee1** [comment] 2022-10-07 06:51
same thing as for Over18

**Comment by ThierryThevenet** [comment] 2022-10-07 21:23
when tyeh card is deleted from home it does not appear on discover

**Comment by hawkbee1** [comment] 2022-10-10 08:51
duplicate of Voucher and membership card is no more available in the Android build 75 #845

**Closed by hawkbee1** 2022-10-10 08:51 UTC
Labels: a V1, Priority, AltMe
