### ISSUE TITLE
Lost all my cards, cannot add them again

### ISSUE THREAD

**Issue by royscheeren** [TalaoDAO/AltMe#2629] opened 2024-04-29 15:26 UTC
I opened the app on android (previous version, I think .22). Saw my cards flashing and then disappeared. I only see the Add Cards button. 

When clicking that button, the discover page no longer shows the tz ownership card and when trying to validate my email, I receive a code, but when I fill in the code and return to the app, the app says "Request not supported".

I experience the same problem on iPhone when trying to add an email ownership card.

**Comment by ThierryThevenet** [comment] 2024-05-01 08:18
The email problem has been fixed (issuer side, no new build)
About the tezos owner ship card : if the VC is not issued yet, one can see a GET card in the Discover (it is just an issuer button indeed). When the VC is issued, the VC is visible  in My wallet and the GET card is not visible anymore in the Discover because we dont want the user to issue 2 VCs of this type. Is the behavior different ?

**Comment by royscheeren** [comment] 2024-05-01 08:38
Yes, the VC disappeared from My Wallet after I had added it, but does not show back up in the Discover tab. So both my wallet and discover now dont have the ownership card.

**Comment by royscheeren** [comment] 2024-05-01 08:43
I was able to add email back on iphone but not on android.
Android gives me a "This format is not supported" after putting in the pin and selecting the credential.

**Comment by ThierryThevenet** [comment] 2024-05-01 09:30
we dont have anymore the issue with email on android and iphone ?
It was fixed by a server fix so it is quite strange to get the issue on android only.
On android we use the 2.4.28 which is a beta release but the production release 2.4.27 should also work
Do you use a specific profile ?

**Comment by ThierryThevenet** [comment] 2024-05-01 09:46
Same with Tz account VC (imported or not imported), we cannot reproduce the issue. we create, delete, create again, close the app, and it looks fine ?
We here only use the profile "Default" as the VC is in ldp format in this profile. However If you change the profile, the VC could be not visible as the wallet only displays the VCs which are supported by the profile selected. So in practice you could get lots of VCs in the wallet but none of them might be visible if the format is not the right one.

**Comment by royscheeren** [comment] 2024-05-01 11:09
My profile is on default.

I will reset the app again and start from scratch.

**Comment by royscheeren** [comment] 2024-05-01 11:17
I've reset the app (android 2.4.28 (448) Samsung Galaxy A80)
- Created a new account (no import)
- Tried to add email proof
- After filling out pin and selecting the email proof get a notification "This format is not supported"

**Comment by ThierryThevenet** [comment] 2024-05-01 12:15
I have checked the transaction server side, it is fine the credential has been signed and sent to the wallet.
Would it be possible that this email was requested with Altme and received on Talao ?
If not i would propose to organise a video call when you are available as i cannot reproduce the problem even with a Samsung.

**Closed** 2024-05-01 14:04 UTC
Labels: bug, NO GO
