### ISSUE TITLE
Beacon : Add Back button aside "Confirm" when buying a NFT

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#764] opened 2022-09-24 17:16 UTC

**Comment by hawkbee1** [comment] 2022-09-29 07:11
duplicate of [Beacon operation: Add Cancel Button next to send/sign button#763](https://github.com/TalaoDAO/AltMe/issues/763)

**Closed by hawkbee1** 2022-09-29 07:11 UTC
Labels: a V1, beacon, AltMe
