### ISSUE TITLE
Talao wallet , issue with pop up message on card details

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#1472] opened 2023-03-15 18:51 UTC
![File(12)](https://user-images.githubusercontent.com/32768069/225413374-d87c83a6-1289-4456-ae97-ff2839809c62.jpg)

**Comment by hawkbee1** [comment] 2023-03-20 06:55
duplicate of 
Talao : pop up on description on card details is white (text color issue) #1485

**Closed by hawkbee1** 2023-03-20 06:55 UTC
Labels: bug, NO GO, talao
