### ISSUE TITLE
membership from discover: check if user as good credentials to present

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#628] opened 2022-08-30 14:10 UTC
**membership card** we check if user a good credentials*
If user has the good credentials => proceed to membership card
If user don't have the good credentials => Don't show card in discover

* good credentials: age range + nationality + addresse tezos

**Comment by hawkbee1** [comment] 2022-09-08 07:20
M size tee-shirt

**Comment by hawkbee1** [comment] 2022-09-27 08:26
2 options qui couvrent aussi ticket referal => hard coded ou credential manifest reçu.

**Comment by hawkbee1** [comment] 2022-09-28 15:28
Waiting for more offers in discover

**Comment by bibash28** [comment] 2022-09-29 10:44
duplicate of https://github.com/TalaoDAO/AltMe/issues/785

**Closed by bibash28** 2022-09-29 10:44 UTC
Labels: a V1
